/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as MinhaRotaRouteImport } from './routes/minha-rota'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NucleoIdRouteImport } from './routes/nucleo.$id'
import { Route as ModuloSlugRouteImport } from './routes/modulo.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaRotaRoute = MinhaRotaRouteImport.update({
  id: '/minha-rota',
  path: '/minha-rota',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NucleoIdRoute = NucleoIdRouteImport.update({
  id: '/nucleo/$id',
  path: '/nucleo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloSlugRoute = ModuloSlugRouteImport.update({
  id: '/modulo/$slug',
  path: '/modulo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/minha-rota': typeof MinhaRotaRoute
  '/sobre': typeof SobreRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/nucleo/$id': typeof NucleoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/minha-rota': typeof MinhaRotaRoute
  '/sobre': typeof SobreRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/nucleo/$id': typeof NucleoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/minha-rota': typeof MinhaRotaRoute
  '/sobre': typeof SobreRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/nucleo/$id': typeof NucleoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/minha-rota'
    | '/sobre'
    | '/modulo/$slug'
    | '/nucleo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/minha-rota'
    | '/sobre'
    | '/modulo/$slug'
    | '/nucleo/$id'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/minha-rota'
    | '/sobre'
    | '/modulo/$slug'
    | '/nucleo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  MinhaRotaRoute: typeof MinhaRotaRoute
  SobreRoute: typeof SobreRoute
  ModuloSlugRoute: typeof ModuloSlugRoute
  NucleoIdRoute: typeof NucleoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-rota': {
      id: '/minha-rota'
      path: '/minha-rota'
      fullPath: '/minha-rota'
      preLoaderRoute: typeof MinhaRotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nucleo/$id': {
      id: '/nucleo/$id'
      path: '/nucleo/$id'
      fullPath: '/nucleo/$id'
      preLoaderRoute: typeof NucleoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$slug': {
      id: '/modulo/$slug'
      path: '/modulo/$slug'
      fullPath: '/modulo/$slug'
      preLoaderRoute: typeof ModuloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  MinhaRotaRoute: MinhaRotaRoute,
  SobreRoute: SobreRoute,
  ModuloSlugRoute: ModuloSlugRoute,
  NucleoIdRoute: NucleoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
