/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AoVivoRouteImport } from './routes/ao-vivo'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CertificadosRouteImport } from './routes/certificados'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as MinhaRotaRouteImport } from './routes/minha-rota'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ModuloSlugRouteImport } from './routes/modulo.$slug'
import { Route as NucleoIdRouteImport } from './routes/nucleo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AoVivoRoute = AoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadosRoute = CertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaRotaRoute = MinhaRotaRouteImport.update({
  id: '/minha-rota',
  path: '/minha-rota',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloSlugRoute = ModuloSlugRouteImport.update({
  id: '/modulo/$slug',
  path: '/modulo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NucleoIdRoute = NucleoIdRouteImport.update({
  id: '/nucleo/$id',
  path: '/nucleo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/certificados': typeof CertificadosRoute
  '/comunidade': typeof ComunidadeRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/minha-rota': typeof MinhaRotaRoute
  '/sobre': typeof SobreRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/nucleo/$id': typeof NucleoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/certificados': typeof CertificadosRoute
  '/comunidade': typeof ComunidadeRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/minha-rota': typeof MinhaRotaRoute
  '/sobre': typeof SobreRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/nucleo/$id': typeof NucleoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/certificados': typeof CertificadosRoute
  '/comunidade': typeof ComunidadeRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/minha-rota': typeof MinhaRotaRoute
  '/sobre': typeof SobreRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/nucleo/$id': typeof NucleoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ao-vivo'
    | '/biblioteca'
    | '/cadastro'
    | '/certificados'
    | '/comunidade'
    | '/login'
    | '/loja'
    | '/minha-rota'
    | '/sobre'
    | '/modulo/$slug'
    | '/nucleo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ao-vivo'
    | '/biblioteca'
    | '/cadastro'
    | '/certificados'
    | '/comunidade'
    | '/login'
    | '/loja'
    | '/minha-rota'
    | '/sobre'
    | '/modulo/$slug'
    | '/nucleo/$id'
  id:
    | '__root__'
    | '/'
    | '/ao-vivo'
    | '/biblioteca'
    | '/cadastro'
    | '/certificados'
    | '/comunidade'
    | '/login'
    | '/loja'
    | '/minha-rota'
    | '/sobre'
    | '/modulo/$slug'
    | '/nucleo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AoVivoRoute: typeof AoVivoRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CadastroRoute: typeof CadastroRoute
  CertificadosRoute: typeof CertificadosRoute
  ComunidadeRoute: typeof ComunidadeRoute
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRoute
  MinhaRotaRoute: typeof MinhaRotaRoute
  SobreRoute: typeof SobreRoute
  ModuloSlugRoute: typeof ModuloSlugRoute
  NucleoIdRoute: typeof NucleoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao-vivo': {
      id: '/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/ao-vivo'
      preLoaderRoute: typeof AoVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificados': {
      id: '/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof CertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-rota': {
      id: '/minha-rota'
      path: '/minha-rota'
      fullPath: '/minha-rota'
      preLoaderRoute: typeof MinhaRotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$slug': {
      id: '/modulo/$slug'
      path: '/modulo/$slug'
      fullPath: '/modulo/$slug'
      preLoaderRoute: typeof ModuloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nucleo/$id': {
      id: '/nucleo/$id'
      path: '/nucleo/$id'
      fullPath: '/nucleo/$id'
      preLoaderRoute: typeof NucleoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AoVivoRoute: AoVivoRoute,
  BibliotecaRoute: BibliotecaRoute,
  CadastroRoute: CadastroRoute,
  CertificadosRoute: CertificadosRoute,
  ComunidadeRoute: ComunidadeRoute,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRoute,
  MinhaRotaRoute: MinhaRotaRoute,
  SobreRoute: SobreRoute,
  ModuloSlugRoute: ModuloSlugRoute,
  NucleoIdRoute: NucleoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
